Split and add repeated argument attribute tests

diff --git a/bin/parseargs_tests b/bin/parseargs_tests
--- a/bin/parseargs_tests
+++ b/bin/parseargs_tests
@@ -946,7 +946,7 @@ options_may_have_short_and_or_long_names_but_each_must_be_unique_in_its_namespac
   REQUIRE_FALSE "${is_parser}"  
 }
 
-argument_attributes_cannot_be_repeated_in_single_parseargs_add_argument_call() {
+argument_name_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call() {
   local parser="$(parseargs_new_argument_parser)"
   local returned_error=""
   local is_parser=false
@@ -955,22 +955,119 @@ argument_attributes_cannot_be_repeated_in_single_parseargs_add_argument_call() {
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "name" "once"
   is_parser="parseargs_is_argument_parser  ${returned_error}"
   REQUIRE -n "${is_parser}"
-  REQUIRE_FALSE "${is_parser}"  
+  REQUIRE_FALSE "${is_parser}"
+}
+
+argument_short_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  local is_parser=false
   returned_error="$(parseargs_add_argument "${parser}" "short" "X" "short" "Y" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "short" "once"
   is_parser="parseargs_is_argument_parser  ${returned_error}"
   REQUIRE -n "${is_parser}"
   REQUIRE_FALSE "${is_parser}"  
+}
+
+argument_long_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  local is_parser=false
   returned_error="$(parseargs_add_argument "${parser}" "long" "eggs" "long" "why" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "long" "once"
   is_parser="parseargs_is_argument_parser  ${returned_error}"
   REQUIRE -n "${is_parser}"
   REQUIRE_FALSE "${is_parser}"  
-
-# add other attributes as support is added...
 }
+
+argument_destination_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  local is_parser=false
+  returned_error="$(parseargs_add_argument "${parser}" "destination" "eggs" "destination" "why" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "destination" "once"
+  is_parser="parseargs_is_argument_parser  ${returned_error}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE_FALSE "${is_parser}"  
+}
+
+argument_action_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  local is_parser=false
+  returned_error="$(parseargs_add_argument "${parser}" "action" "store_true" "action" "store_false" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "action" "once"
+  is_parser="parseargs_is_argument_parser  ${returned_error}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE_FALSE "${is_parser}"  
+}
+
+argument_nargs_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  local is_parser=false
+  returned_error="$(parseargs_add_argument "${parser}" "nargs" "2" "nargs" "*" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nargs" "once"
+  is_parser="parseargs_is_argument_parser  ${returned_error}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE_FALSE "${is_parser}"  
+}
+
+argument_const_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  local is_parser=false
+  returned_error="$(parseargs_add_argument "${parser}" "const" "yes" "const" "no" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "const" "once"
+  is_parser="parseargs_is_argument_parser  ${returned_error}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE_FALSE "${is_parser}"  
+}
+
+argument_default_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  local is_parser=false
+  returned_error="$(parseargs_add_argument "${parser}" "default" "yes" "default" "no" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "default" "once"
+  is_parser="parseargs_is_argument_parser  ${returned_error}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE_FALSE "${is_parser}"  
+}
+
+argument_required_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  local is_parser=false
+  returned_error="$(parseargs_add_argument "${parser}" "required" "true" "required" "True" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "required" "once"
+  is_parser="parseargs_is_argument_parser  ${returned_error}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE_FALSE "${is_parser}"  
+}
+
+argument_choices_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  local is_parser=false
+  local choices="$(dict_declare_simple "FROM" "_" "TO" "_")"
+  returned_error="$(parseargs_add_argument "${parser}" "choices" "${choices}" "choices" "${choices}" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "choices" "once"
+  is_parser="parseargs_is_argument_parser  ${returned_error}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE_FALSE "${is_parser}"  
+}
+
+# add other xxx_attribute_cannot_be_repeated tests as support is added...
 
 extra_positional_arguments_ignored_when_parsed() {
   local parser="$(parseargs_new_argument_parser)"
@@ -1269,7 +1366,16 @@ TEST argument_cannot_be_both_positional_and_optional
 TEST argument_needs_name_or_long_and_or_short_attribute
 TEST short_option_must_be_single_character
 TEST options_may_have_short_and_or_long_names_but_each_must_be_unique_in_its_namespace
-TEST argument_attributes_cannot_be_repeated_in_single_parseargs_add_argument_call
+TEST argument_name_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call
+TEST argument_short_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call
+TEST argument_long_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call
+TEST argument_destination_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call
+TEST argument_action_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call
+TEST argument_nargs_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call
+TEST argument_const_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call
+TEST argument_default_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call
+TEST argument_required_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call
+TEST argument_choices_attribute_cannot_be_repeated_in_single_parseargs_add_argument_call
 TEST extra_positional_arguments_ignored_when_parsed
 TEST extra_positional_multi_arguments_ignored_when_parsed
 TEST too_few_positional_arguments_is_an_error_when_parsed
