Add checks and test for missing optional arguments  - note: an option string starting with hyphen following one requring an    argument beomes the argument of the preceding option: -o -p - -p    is the argument value for option -o.

diff --git a/bin/parseargs_tests b/bin/parseargs_tests
--- a/bin/parseargs_tests
+++ b/bin/parseargs_tests
@@ -241,6 +241,25 @@ unknown_short_option_is_an_error_when_parsed() {
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nknown" "option"
 }
 
+missing_short_option_argument_is_an_error_when_parsed() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  parser="$(parseargs_add_argument "${parser}" "short" "o" destination "argument")"
+  returned_error="$(parseargs_parse_arguments "${parser}" "-o" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
+
+# The following is currently OK for -o option, has argument value -f but
+# warning on unexpected positional argument "following-value"
+# NOTE: making argument values starting wuth hyphens an error is fraught
+# with problems - what about negative numbers -123 and the like or cases
+# where another command line (fragment) is passed in or a file name
+# just happens to start with a hyphen ...
+  parser="$(parseargs_add_argument "${parser}" "short" "f" destination "following")"
+  returned_error="$(parseargs_parse_arguments "${parser}" "-o" "-f" "following-value" 2>&1)"
+  CHECK $? -eq 0
+}
+
 #set -x
 TEST parsearg_functions_complain_if_parameter_not_a_parseargs_parser
 TEST make_arg_parser_with_positional_arguments_and_parse_some_arguments
@@ -255,4 +274,5 @@ TEST argument_attributes_cannot_be_repeated_in_single_parseargs_add_argument_cal
 TEST extra_positional_arguments_ignored_when_parsed
 TEST too_few_positional_arguments_is_an_error_when_parsed
 TEST unknown_short_option_is_an_error_when_parsed
+TEST missing_short_option_argument_is_an_error_when_parsed
 PRINT_TEST_COUNTS
