Add test for argument separator  - includes updating missing agument tests

diff --git a/bin/parseargs_tests b/bin/parseargs_tests
--- a/bin/parseargs_tests
+++ b/bin/parseargs_tests
@@ -381,23 +381,38 @@ unknown_long_option_is_an_error_when_parsed() {
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nknown" "option"
 }
 
+argument_values_starting_with_hyphens_must_be_preceded_by_the_argument_separator() {
+  local parser="$(parseargs_new_argument_parser)"
+  parser="$(parseargs_add_argument "${parser}" "short" "o" "long" "option")"
+  parser="$(parseargs_add_argument "${parser}" "short" "f" "long" "following")"
+  parser="$(parseargs_add_argument "${parser}" "name" "positional")"
+  local arguments="$(parseargs_parse_arguments "${parser}" "-o" "--" "--following" \
+                                                           "--" "--positional--" \
+                                                           "--following" -- "-o")"
+  CHECK $? -eq 0
+  CHECK "$(dict_get "${arguments}" "option")" = "--following"
+  CHECK "$(dict_get "${arguments}" "following")" = "-o"
+  CHECK "$(dict_get "${arguments}" "positional")" = "--positional--"
+}
+
 missing_short_option_argument_is_an_error_when_parsed() {
   local parser="$(parseargs_new_argument_parser)"
   local returned_error=""
-  parser="$(parseargs_add_argument "${parser}" "short" "o" destination "argument")"
+  parser="$(parseargs_add_argument "${parser}" "short" "o" "destination" "argument")"
   returned_error="$(parseargs_parse_arguments "${parser}" "-o" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
-
-# The following is currently OK for -o option, has argument value -f but
-# warning on unexpected positional argument "following-value"
-# NOTE: making argument values starting with hyphens an error is fraught
-# with problems - what about negative numbers -123 and the like or cases
-# where another command line (fragment) is passed in or a file name
-# just happens to start with a hyphen ...
-  parser="$(parseargs_add_argument "${parser}" "short" "f" destination "following")"
+#
+# Arguments starting with hyphens are not allowed unless preceded by 
+# -- , the argument separator
+#
+  parser="$(parseargs_add_argument "${parser}" "short" "f" "destination" "following")"
   returned_error="$(parseargs_parse_arguments "${parser}" "-o" "-f" "following-value" 2>&1)"
-  CHECK $? -eq 0
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
+  returned_error="$(parseargs_parse_arguments "${parser}" "-o" "--" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
 }
 
 missing_long_option_argument_is_an_error_when_parsed() {
@@ -407,16 +422,17 @@ missing_long_option_argument_is_an_error_when_parsed() {
   returned_error="$(parseargs_parse_arguments "${parser}" "--option" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
-
-# The following is currently OK for --option option, has argument value
-# --following but warning on unexpected positional argument "following-value"
-# NOTE: making argument values starting with double hyphens an error is
-# fraught with problems, though less so than single hyphens - e.g. cases
-# where another command line (fragment) is passed in or a file name
-# just happens to start with a two hyphens ...
+#
+# Arguments starting with hyphens are not allowed unless preceded by 
+# -- , the argument separator
+#
   parser="$(parseargs_add_argument "${parser}" "long" "following")"
   returned_error="$(parseargs_parse_arguments "${parser}" "--option" "--following" "following-value" 2>&1)"
-  CHECK $? -eq 0
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
+  returned_error="$(parseargs_parse_arguments "${parser}" "--option" "--" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
 }
 
 #set -x
@@ -441,6 +457,7 @@ TEST extra_positional_arguments_ignored_when_parsed
 TEST too_few_positional_arguments_is_an_error_when_parsed
 TEST unknown_short_option_is_an_error_when_parsed
 TEST unknown_long_option_is_an_error_when_parsed
+TEST argument_values_starting_with_hyphens_must_be_preceded_by_the_argument_separator
 TEST missing_short_option_argument_is_an_error_when_parsed
 TEST missing_long_option_argument_is_an_error_when_parsed
 PRINT_TEST_COUNTS
