Add nargs arg attribute with value validity tests.   -- todo: use the nargs attribute when parsing arguments

diff --git a/bin/parseargs_tests b/bin/parseargs_tests
--- a/bin/parseargs_tests
+++ b/bin/parseargs_tests
@@ -153,6 +153,92 @@ make_arg_parser_with_required_optional_arguments_and_parse_some_arguments() {
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "--target" "equired"
 }
 
+argument_nargs_attribute_can_be_in_range_integer() {
+  local parser="$(parseargs_new_argument_parser)"
+  local is_parser=false
+  is_parser="parseargs_is_argument_parser  ${parser}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE "${is_parser}"
+  parser="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "1")"
+  CHECK $? -eq 0
+  is_parser="parseargs_is_argument_parser  ${parser}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE "${is_parser}"
+  parser="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "${__PARSEARGS_MAX_NARGS__}")"
+  CHECK $? -eq 0
+  is_parser="parseargs_is_argument_parser  ${parser}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE "${is_parser}"
+}
+
+argument_nargs_attribute_can_be_single_glob_character() {
+  local parser="$(parseargs_new_argument_parser)"
+  local is_parser=false
+  is_parser="parseargs_is_argument_parser  ${parser}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE "${is_parser}"
+  parser="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "?")"
+  CHECK $? -eq 0
+  is_parser="parseargs_is_argument_parser  ${parser}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE "${is_parser}"
+  parser="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "*")"
+  CHECK $? -eq 0
+  is_parser="parseargs_is_argument_parser  ${parser}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE "${is_parser}"
+  parser="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "+")"
+  CHECK $? -eq 0
+  is_parser="parseargs_is_argument_parser  ${parser}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE "${is_parser}"
+}
+
+argument_nargs_attribute_cannot_be_out_of_range_integer() {
+  local parser="$(parseargs_new_argument_parser)"
+  local is_parser=false
+  local returned_error=""
+  is_parser="parseargs_is_argument_parser  ${parser}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE "${is_parser}"
+  returned_error="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "0" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nargs" "invalid"
+  returned_error="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "$(( ${__PARSEARGS_MAX_NARGS__}+1 ))" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nargs" "invalid"
+}
+
+argument_nargs_attribute_cannot_be_non_glob_non_interger_value() {
+  local parser="$(parseargs_new_argument_parser)"
+  local is_parser=false
+  local returned_error=""
+  is_parser="parseargs_is_argument_parser  ${parser}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE "${is_parser}"
+  returned_error="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "three" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nargs" "invalid"
+  returned_error="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "-1" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nargs" "invalid"
+  returned_error="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "3.14" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nargs" "invalid"
+  returned_error="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "??" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nargs" "invalid"
+  returned_error="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "**" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nargs" "invalid"
+  returned_error="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "++" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nargs" "invalid"
+  returned_error="$(parseargs_add_argument "${parser}" "name" "arguments" "nargs" "?*+" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "nargs" "invalid"
+}
+
 argument_cannot_be_both_positional_and_optional() {
   local parser="$(parseargs_new_argument_parser)"
   local returned_error=""
@@ -342,6 +428,10 @@ TEST make_arg_parser_with_long_optional_arguments_and_parse_some_arguments
 TEST make_arg_parser_with_positional_and_short_and_long_optional_arguments_and_parse_some_arguments
 TEST make_arg_parser_with_optional_arguments_with_defaults_and_parse_some_arguments
 TEST make_arg_parser_with_required_optional_arguments_and_parse_some_arguments
+TEST argument_nargs_attribute_can_be_in_range_integer
+TEST argument_nargs_attribute_can_be_single_glob_character
+TEST argument_nargs_attribute_cannot_be_out_of_range_integer
+TEST argument_nargs_attribute_cannot_be_non_glob_non_interger_value
 TEST argument_cannot_be_both_positional_and_optional
 TEST argument_needs_name_or_long_and_or_short_attribute
 TEST short_option_must_be_single_character
