Add sub_xxx missing positionals tests & fix parseargs   - move check for missing positional arguments to validate and fixup   - fix tracking of current positional for sub commands and across validate      and fixup sub_command/argument context switching

diff --git a/bin/parseargs_tests b/bin/parseargs_tests
--- a/bin/parseargs_tests
+++ b/bin/parseargs_tests
@@ -215,14 +215,14 @@ make_arg_parser_with_positional_sub_commands_and_parse_some_arguments() {
   parser="$(parseargs_add_sub_parser "${parser}" "delete" "${delcmdparser}" )"
   local arguments="$(parseargs_parse_arguments "${parser}" "copy" "FROM" "TO")"
   local command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "4"
+  CHECK "$(dict_size "${command}")" = "5"
   CHECK "$(dict_get "${command}" "source")" = "FROM"
   CHECK "$(dict_get "${command}" "target")" = "TO"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "copy"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "copy"
   arguments="$(parseargs_parse_arguments "${parser}" "delete" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "delete"
@@ -236,25 +236,25 @@ make_arg_parser_with_positional_sub_commands_and_alias_and_parse_some_arguments(
   parser="$(parseargs_add_sub_parser "${parser}" "delete" "${delcmdparser}" 'del' 'remove' 'rm')"
   local arguments="$(parseargs_parse_arguments "${parser}" "delete" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "delete"
   arguments="$(parseargs_parse_arguments "${parser}" "del" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "del"
   arguments="$(parseargs_parse_arguments "${parser}" "remove" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "remove"
   arguments="$(parseargs_parse_arguments "${parser}" "rm" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "rm"
@@ -649,14 +649,14 @@ make_arg_parser_with_short_optional_sub_commands_and_parse_some_arguments() {
   parser="$(parseargs_add_sub_parser "${parser}" "delete" "${delcmdparser}" )"
   local arguments="$(parseargs_parse_arguments "${parser}" "-c" "copy" "FROM" "TO")"
   local command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "4"
+  CHECK "$(dict_size "${command}")" = "5"
   CHECK "$(dict_get "${command}" "source")" = "FROM"
   CHECK "$(dict_get "${command}" "target")" = "TO"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "copy"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "copy"
   arguments="$(parseargs_parse_arguments "${parser}" "-c" "delete" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "delete"
@@ -670,25 +670,25 @@ make_arg_parser_with_short_optional_sub_commands_and_alias_and_parse_some_argume
   parser="$(parseargs_add_sub_parser "${parser}" "delete" "${delcmdparser}" 'del' 'remove' 'rm')"
   local arguments="$(parseargs_parse_arguments "${parser}" '-c' "delete" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "delete"
   arguments="$(parseargs_parse_arguments "${parser}" '-c' "del" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "del"
   arguments="$(parseargs_parse_arguments "${parser}" '-c' "remove" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "remove"
   arguments="$(parseargs_parse_arguments "${parser}" '-c' "rm" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "rm"
@@ -703,7 +703,7 @@ make_arg_parser_with_short_optional_sub_command_with_default_and_parse_no_sub_ar
 
   local arguments="$(parseargs_parse_arguments "${parser}" "-c" "count")"
   local command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "count")" = "0"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "count"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "count"
@@ -1127,14 +1127,14 @@ make_arg_parser_with_long_optional_sub_commands_and_parse_some_arguments() {
   parser="$(parseargs_add_sub_parser "${parser}" "delete" "${delcmdparser}" )"
   local arguments="$(parseargs_parse_arguments "${parser}" "--command" "copy" "FROM" "TO")"
   local command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "4"
+  CHECK "$(dict_size "${command}")" = "5"
   CHECK "$(dict_get "${command}" "source")" = "FROM"
   CHECK "$(dict_get "${command}" "target")" = "TO"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "copy"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "copy"
   arguments="$(parseargs_parse_arguments "${parser}" "--command" "delete" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "delete"
@@ -1148,25 +1148,25 @@ make_arg_parser_with_long_optional_sub_commands_and_alias_and_parse_some_argumen
   parser="$(parseargs_add_sub_parser "${parser}" "delete" "${delcmdparser}" 'del' 'remove' 'rm')"
   local arguments="$(parseargs_parse_arguments "${parser}" '--command' "delete" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "delete"
   arguments="$(parseargs_parse_arguments "${parser}" '--command' "del" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "del"
   arguments="$(parseargs_parse_arguments "${parser}" '--command' "remove" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "remove"
   arguments="$(parseargs_parse_arguments "${parser}" '--command' "rm" "UNLOVED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "UNLOVED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "rm"
@@ -1181,7 +1181,7 @@ make_arg_parser_with_long_optional_sub_command_with_default_and_parse_no_sub_arg
 
   local arguments="$(parseargs_parse_arguments "${parser}" "--command" "count")"
   local command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "value")" = "0"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "count"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "count"
@@ -1346,7 +1346,21 @@ make_arg_parser_with_required_optional_sub_commands_and_parse_some_arguments() {
   parser="$(parseargs_add_sub_parser "${parser}" "delete" "${delcmdparser}" )"
   local arguments="$(parseargs_parse_arguments "${parser}" "--command" "delete" "NOT_NEEDED")"
   command="$(dict_get "${arguments}" "command")"
-  CHECK "$(dict_size "${command}")" = "3"
+  CHECK "$(dict_size "${command}")" = "4"
+  CHECK "$(dict_get "${command}" "item")" = "NOT_NEEDED"
+  CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
+  CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "delete"
+}
+
+make_arg_parser_with_required_optional_sub_arguments_and_parse_some_arguments() {
+  local parser="$(parseargs_new_argument_parser)"
+  parser="$(parseargs_add_argument "${parser}" 'long' "command" 'action' 'sub_argument' 'required' 'true')"
+  local delcmdparser="$(parseargs_new_argument_parser)"
+  delcmdparser="$(parseargs_add_argument "${delcmdparser}" "name" "item")"
+  parser="$(parseargs_add_sub_parser "${parser}" "delete" "${delcmdparser}" )"
+  local arguments="$(parseargs_parse_arguments "${parser}" "--command" "delete" "NOT_NEEDED")"
+  command="$(dict_get "${arguments}" "command")"
+  CHECK "$(dict_size "${command}")" = "4"
   CHECK "$(dict_get "${command}" "item")" = "NOT_NEEDED"
   CHECK "$(dict_get "${command}" "__sub_command__")" = "delete"
   CHECK "$(dict_get "${command}" "__sub_command_alias__")" = "delete"
@@ -1369,6 +1383,22 @@ parser_with_missing_required_optional_arguments_is_an_error() {
 parser_with_missing_required_optional_sub_command_is_an_error() {
   local parser="$(parseargs_new_argument_parser)"
   parser="$(parseargs_add_argument "${parser}" 'long' "command" 'action' 'sub_command' 'required' 'true')"
+  local copycmdparser="$(parseargs_new_argument_parser)"
+  copycmdparser="$(parseargs_add_argument "${copycmdparser}" "name" "source")"
+  copycmdparser="$(parseargs_add_argument "${copycmdparser}" "name" "target")"
+  local delcmdparser="$(parseargs_new_argument_parser)"
+  delcmdparser="$(parseargs_add_argument "${delcmdparser}" "name" "item")"
+  parser="$(parseargs_add_sub_parser "${parser}" "copy" "${copycmdparser}" )"
+  parser="$(parseargs_add_sub_parser "${parser}" "delete" "${delcmdparser}" )"
+  local returned_error=""
+  returned_error="$(parseargs_parse_arguments "${parser}"  2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "--command" "equired"
+}
+
+parser_with_missing_required_optional_sub_argument_is_an_error() {
+  local parser="$(parseargs_new_argument_parser)"
+  parser="$(parseargs_add_argument "${parser}" 'long' "command" 'action' 'sub_argument' 'required' 'true')"
   local copycmdparser="$(parseargs_new_argument_parser)"
   copycmdparser="$(parseargs_add_argument "${copycmdparser}" "name" "source")"
   copycmdparser="$(parseargs_add_argument "${copycmdparser}" "name" "target")"
@@ -1626,6 +1656,32 @@ too_few_positional_arguments_is_an_error_when_parsed() {
   parser="$(parseargs_add_argument "${parser}" "name" "source")"
   parser="$(parseargs_add_argument "${parser}" "name" "target")"
   returned_error="$(parseargs_parse_arguments "${parser}" "FROM" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing" "ositional"
+}
+
+too_few_sub_command_positional_arguments_is_an_error_when_parsed() {
+  local parser="$(parseargs_new_argument_parser)"
+  parser="$(parseargs_add_argument "${parser}" 'short' 'c' "destination" "command" 'action' 'sub_command' )"
+  local subparser="$(parseargs_new_argument_parser)"
+  subparser="$(parseargs_add_argument "${subparser}" "name" "source")"
+  subparser="$(parseargs_add_argument "${subparser}" "name" "target")"
+  local returned_error=""
+  parser="$(parseargs_add_sub_parser "${parser}" "copy" "${subparser}" )"
+  returned_error="$(parseargs_parse_arguments "${parser}" -c copy "FROM" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing" "ositional"
+}
+
+too_few_sub_argument_positional_arguments_is_an_error_when_parsed() {
+  local parser="$(parseargs_new_argument_parser)"
+  parser="$(parseargs_add_argument "${parser}" 'short' 'c' "destination" "command" 'action' 'sub_argument' )"
+  local subparser="$(parseargs_new_argument_parser)"
+  subparser="$(parseargs_add_argument "${subparser}" "name" "source")"
+  subparser="$(parseargs_add_argument "${subparser}" "name" "target")"
+  local returned_error=""
+  parser="$(parseargs_add_sub_parser "${parser}" "copy" "${subparser}" )"
+  returned_error="$(parseargs_parse_arguments "${parser}" -c copy "FROM" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing" "ositional"
 }
@@ -2002,7 +2058,7 @@ optional_argument_with_append_const_action_must_specify_const() {
 }
 
 #set -x
-#TEST make_arg_parser_with_short_optional_sub_command_with_default_and_parse_no_sub_arguments
+#TEST parser_with_missing_required_optional_sub_argument_is_an_error
 #PRINT_TEST_COUNTS
 #exit 0
 TEST parsearg_functions_complain_if_parameter_not_a_parseargs_parser
@@ -2099,8 +2155,10 @@ TEST make_arg_parser_with_positional_and_short_and_long_optional_multi_arguments
 TEST make_arg_parser_with_optional_arguments_with_defaults_and_parse_some_arguments
 TEST make_arg_parser_with_required_optional_arguments_and_parse_some_arguments
 TEST make_arg_parser_with_required_optional_sub_commands_and_parse_some_arguments
+TEST make_arg_parser_with_required_optional_sub_arguments_and_parse_some_arguments
 TEST parser_with_missing_required_optional_arguments_is_an_error
 TEST parser_with_missing_required_optional_sub_command_is_an_error
+TEST parser_with_missing_required_optional_sub_argument_is_an_error
 TEST argument_nargs_attribute_can_be_in_range_integer
 TEST argument_nargs_attribute_can_be_single_glob_character
 TEST argument_nargs_attribute_cannot_be_out_of_range_integer
@@ -2122,6 +2180,8 @@ TEST argument_choices_attribute_cannot_be_repeated_in_single_parseargs_add_argum
 TEST extra_positional_arguments_ignored_when_parsed
 TEST extra_positional_multi_arguments_ignored_when_parsed
 TEST too_few_positional_arguments_is_an_error_when_parsed
+TEST too_few_sub_command_positional_arguments_is_an_error_when_parsed
+TEST too_few_sub_argument_positional_arguments_is_an_error_when_parsed
 TEST too_few_positional_multi_arguments_is_an_error_when_parsed
 TEST unknown_short_option_is_an_error_when_parsed
 TEST unknown_long_option_is_an_error_when_parsed
