Add further numeric nargs tests   - complex command parser with multi argument positional,     short and long options. - check too many positional arguments with multi-arguments not an error - check too few positional, long and short optional multi-arguments   are errors.

diff --git a/bin/parseargs_tests b/bin/parseargs_tests
--- a/bin/parseargs_tests
+++ b/bin/parseargs_tests
@@ -216,6 +216,38 @@ make_arg_parser_with_positional_and_short_and_long_optional_arguments_and_parse_
   CHECK "$(dict_get "${arguments}" "action")" = "COPY"
 }
 
+make_arg_parser_with_positional_and_short_and_long_optional_multi_arguments_and_parse_some_arguments() {
+  local parser="$(parseargs_new_argument_parser)"
+  local is_parser=false
+  is_parser="parseargs_is_argument_parser  ${parser}"
+  REQUIRE -n "${is_parser}"
+  REQUIRE "${is_parser}"
+  parser="$(parseargs_add_argument "${parser}" "name" "sources" "nargs" "2")"
+  parser="$(parseargs_add_argument "${parser}" "name" "target")"
+  parser="$(parseargs_add_argument "${parser}" "short" "p" destination "prefixes" "nargs" "2")"
+  parser="$(parseargs_add_argument "${parser}" "short" "s" "destination" "suffixes" "nargs" "3")"
+  parser="$(parseargs_add_argument "${parser}" "long" "actions" "nargs" "2" )"
+  local arguments="$(parseargs_parse_arguments "${parser}" "LEFT" "RIGHT" "-sEPILOGUE" "NOTES" "INDEX" "TO" "--actions" "COPY" "RECURSIVE" "-p" "PRELUDE" "PROLOGUE")"
+  local sources="$(dict_get "${arguments}" "sources")"
+  CHECK "$(dict_size "${sources}")" = "2"
+  CHECK "$(dict_get "${sources}" "0")" = "LEFT"
+  CHECK "$(dict_get "${sources}" "1")" = "RIGHT"
+  CHECK "$(dict_get "${arguments}" "target")" = "TO"
+  local suffixes="$(dict_get "${arguments}" "suffixes")"
+  CHECK "$(dict_size "${suffixes}")" = "3"
+  CHECK "$(dict_get "${suffixes}" "0")" = "EPILOGUE"
+  CHECK "$(dict_get "${suffixes}" "1")" = "NOTES"
+  CHECK "$(dict_get "${suffixes}" "2")" = "INDEX"
+  local prefixes="$(dict_get "${arguments}" "prefixes")"
+  CHECK "$(dict_size "${prefixes}")" = "2"
+  CHECK "$(dict_get "${prefixes}" "0")" = "PRELUDE"
+  CHECK "$(dict_get "${prefixes}" "1")" = "PROLOGUE"
+  local actions="$(dict_get "${arguments}" "actions")"
+  CHECK "$(dict_size "${actions}")" = "2"
+  CHECK "$(dict_get "${actions}" "0")" = "COPY"
+  CHECK "$(dict_get "${actions}" "1")" = "RECURSIVE"
+}
+
 make_arg_parser_with_optional_arguments_with_defaults_and_parse_some_arguments() {
   local parser="$(parseargs_new_argument_parser)"
   local is_parser=false
@@ -449,6 +481,18 @@ extra_positional_arguments_ignored_when_parsed() {
   CHECK "$(dict_get "${arguments}" "target")" = "TO"
 }
 
+extra_positional_multi_arguments_ignored_when_parsed() {
+  local parser="$(parseargs_new_argument_parser)"
+  parser="$(parseargs_add_argument "${parser}" "name" "sources" "nargs" "2")"
+  parser="$(parseargs_add_argument "${parser}" "name" "target")"
+  local arguments="$(parseargs_parse_arguments "${parser}" "LEFT" "RIGHT" "TO" "EXTRA" 2>/dev/null)"
+  local sources="$(dict_get "${arguments}" "sources")"
+  CHECK "$(dict_size "${sources}")" = "2"
+  CHECK "$(dict_get "${sources}" "0")" = "LEFT"
+  CHECK "$(dict_get "${sources}" "1")" = "RIGHT"
+  CHECK "$(dict_get "${arguments}" "target")" = "TO"
+}
+
 too_few_positional_arguments_is_an_error_when_parsed() {
   local parser="$(parseargs_new_argument_parser)"
   local returned_error=""
@@ -456,7 +500,17 @@ too_few_positional_arguments_is_an_error_when_parsed() {
   parser="$(parseargs_add_argument "${parser}" "name" "target")"
   returned_error="$(parseargs_parse_arguments "${parser}" "FROM" 2>&1)"
   CHECK $? -eq 1
-  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "few" "positional"
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "few" "ositional"
+}
+
+too_few_positional_multi_arguments_is_an_error_when_parsed() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  parser="$(parseargs_add_argument "${parser}" "name" "source")"
+  parser="$(parseargs_add_argument "${parser}" "name" "targets" "nargs" "2")"
+  returned_error="$(parseargs_parse_arguments "${parser}" "FROM" "LEFT" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing" "ositional"
 }
 
 unknown_short_option_is_an_error_when_parsed() {
@@ -496,15 +550,27 @@ missing_short_option_argument_is_an_error_when_parsed() {
   returned_error="$(parseargs_parse_arguments "${parser}" "-o" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
-#
-# Arguments starting with hyphens are not allowed unless preceded by 
-# -- , the argument separator
-#
   parser="$(parseargs_add_argument "${parser}" "short" "f" "destination" "following")"
   returned_error="$(parseargs_parse_arguments "${parser}" "-o" "-f" "following-value" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
   returned_error="$(parseargs_parse_arguments "${parser}" "-o" "--" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
+}
+
+missing_short_option_multi_argument_is_an_error_when_parsed() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  parser="$(parseargs_add_argument "${parser}" "short" "o" "destination" "argument" "nargs" "2")"
+  returned_error="$(parseargs_parse_arguments "${parser}" "-o" "onlyone" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
+  parser="$(parseargs_add_argument "${parser}" "short" "f" "destination" "following")"
+  returned_error="$(parseargs_parse_arguments "${parser}" "-o" "onlyone" "-f" "following-value" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
+  returned_error="$(parseargs_parse_arguments "${parser}" "-o" "onlyone" "--" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
 }
@@ -516,15 +582,27 @@ missing_long_option_argument_is_an_error_when_parsed() {
   returned_error="$(parseargs_parse_arguments "${parser}" "--option" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
-#
-# Arguments starting with hyphens are not allowed unless preceded by 
-# -- , the argument separator
-#
   parser="$(parseargs_add_argument "${parser}" "long" "following")"
   returned_error="$(parseargs_parse_arguments "${parser}" "--option" "--following" "following-value" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
   returned_error="$(parseargs_parse_arguments "${parser}" "--option" "--" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
+}
+
+missing_long_option_multi_argument_is_an_error_when_parsed() {
+  local parser="$(parseargs_new_argument_parser)"
+  local returned_error=""
+  parser="$(parseargs_add_argument "${parser}" "long" "option" "nargs" "2")"
+  returned_error="$(parseargs_parse_arguments "${parser}" "--option" "onlyone" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
+  parser="$(parseargs_add_argument "${parser}" "long" "following")"
+  returned_error="$(parseargs_parse_arguments "${parser}" "--option" "onlyone" "--following" "following-value" 2>&1)"
+  CHECK $? -eq 1
+  CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
+  returned_error="$(parseargs_parse_arguments "${parser}" "--option" "onlyone" "--" 2>&1)"
   CHECK $? -eq 1
   CHECK_CONTAINS_ALL "${returned_error}" "ERROR" "missing"
 }
@@ -542,6 +620,7 @@ TEST make_arg_parser_with_long_optional_arguments_and_parse_some_arguments_after
 TEST make_arg_parser_with_long_optional_multi_arguments_and_parse_some_arguments
 TEST make_arg_parser_with_long_optional_multi_arguments_and_parse_some_arguments_after_equals
 TEST make_arg_parser_with_positional_and_short_and_long_optional_arguments_and_parse_some_arguments
+TEST make_arg_parser_with_positional_and_short_and_long_optional_multi_arguments_and_parse_some_arguments
 TEST make_arg_parser_with_optional_arguments_with_defaults_and_parse_some_arguments
 TEST make_arg_parser_with_required_optional_arguments_and_parse_some_arguments
 TEST argument_nargs_attribute_can_be_in_range_integer
@@ -554,10 +633,14 @@ TEST short_option_must_be_single_character
 TEST options_may_have_short_and_or_long_names_but_each_must_be_unique_in_its_namespace
 TEST argument_attributes_cannot_be_repeated_in_single_parseargs_add_argument_call
 TEST extra_positional_arguments_ignored_when_parsed
+TEST extra_positional_multi_arguments_ignored_when_parsed
 TEST too_few_positional_arguments_is_an_error_when_parsed
+TEST too_few_positional_multi_arguments_is_an_error_when_parsed
 TEST unknown_short_option_is_an_error_when_parsed
 TEST unknown_long_option_is_an_error_when_parsed
 TEST argument_values_starting_with_hyphens_must_be_preceded_by_the_argument_separator
 TEST missing_short_option_argument_is_an_error_when_parsed
+TEST missing_short_option_multi_argument_is_an_error_when_parsed
 TEST missing_long_option_argument_is_an_error_when_parsed
+TEST missing_long_option_multi_argument_is_an_error_when_parsed
 PRINT_TEST_COUNTS
